services:
    frankenphp-server:
        image: component_php:latest
        container_name: component_php
        ports:
            - '8080:8080'
        volumes:
            - '$PWD/ComponentPHP:/home/ComponentPHP'
        command: sh -c 'cd /home/ComponentPHP && frankenphp run'
